<?php

function generate(int $numRows)
{
    // initialize the first item in the triangle to 1. That is the constant 
    $res = [[1]];

    // perform a loop the numRows times
    for ($i=1; $i < $numRows; $i++) { 
        // create a temporary variable and append and prepend 0 to the last item in the triangle.
        // If we look at a pascal triangle's diagram, the outermost numbers are generated by adding the upper outermost number to zero
        $temp = [0, ...$res[count($res) - 1], 0];
        // create a row to house the next row we would compute
        $row = [];
        // we create another loop that goes through the last rows in the resulting triangle plus 1 times. 
        // We know every time we compute a new row to the triangle it increases by length 1. 
        // We then compute the new row by adding the current element and the one after and we add it to the new row
        for ($j=0; $j < count($res[count($res) - 1]) + 1; $j++) { 
            array_push($row, $temp[$j] + $temp[$j+1]);
        }

        // We then add the new row to the result array
        array_push($res,$row);
    }
    return $res;

}

print_r(generate(5));